result = [  
  "Word Of Mouth - Per QX",
  "Rendezvous (feat. Leon Thomas) - Tom Budin Remix Radio Edit - Kronic",
  "From the Ghetto - Ben Delay Remix - Saccao",
  "Gassed - TCTS Remix / Radio Edit - WESLEE",
  "Domino - Oxia",
  "All I Want - Bob Moses",
  "What's a Girl to Do - Fatima Yamaha",
  "Promise You - Ben Böhmer",
  "Guilty Love - ZHU",
  "Ada - Jesper Ryom",
  "Handprint (feat. Amina Ya Heard) [Aeroplane Remix] - Detroit's Filthiest",
  "Swell - Original Mix - Mark Mackenzie",
  "Heartburn - Felix Cartal Remix - Wafia",
  "Yeah - Edit - Set Mo",
  "White Dress (feat. Deutsch Duke) - Radio Edit - Set Mo",
  "Karma - Justin Jay",
  "Get Real (Can't Touch Your Love) - Loframes",
  "W / O U - GEMS",
  "Electric Lullaby - Jason Burns Remix - Fish From Japan",
  "You Don't Wanna Be Loved - Radio Edit - Rui Da Silva",
  "Endurance - Road Kahan",
  "Sugar Man (Vanilla Ace Remix) - Yolanda Be Cool",
  "Check It - Original Mix - Kevin McKay",
  "To Dust - Rektchordz Remix - My Digital Enemy",
  "New School Vintage - Atove Remix - dharkfunkh",
  "Mirage - Tvardovsky Remix - Vanilla Ace",
  "Stoli - Martin Landsky Remix - Djuma Soundsystem",
  "Parallels - Jako Diaz",
  "Nasty - Adibu",
  "Trouble - Daniel Fernandes",
  "Jealous - Klokk",
  "Kilo Kill - Klokk",
  "Down and Down - Kalish",
  "Toccata (feat. Mogli) - Gustavo Mota",
  "Fix Yo Lips - Daniel Fernandes",
  "I Can't Dance - Andrey Exx",
  "Drifting - Original Mix - Lee Foss",
  "Get Techy - Platinum Doug",
  "So Bad - VINNE",
  "Whithout You! - Sharam Jey",
  "I Want You Back - Sharam Jey",
  "So Good - Radio mix - Woo2Tech",
  "Hit and Run - Hot Since 82",
  "Walk Alone - Earstrip",
  "Beautiful Day - Earstrip",
  "Northern Lights - Satin Jackets",
  "Prince Of Persia - Simple Symmetry",
  "Into the Wild - Teho",
  "Heaven - Elderbrook Remix - Alex Adair",
  "Eraser - HVOB",
  "Make A Living - Mat.Joe",
  "Swipe The Card - Mat.Joe",
  "Listen - Max Chapman",
  "Zulu - Original Mix - Max Chapman",
  "Do What Ya Like - TR436 - Max Chapman",
  "Feel My Needs - Weiss (UK)",
  "Rebirth - Original Mix - Betoko",
  "Hold On We're Going Home - ASTR",
  "Got A Feeling - Josh Butler",
  "Time and Time Again - Original Mix - James Mac",
  "Great Spirit - Armin van Buuren",
  "Self Control (feat. Lara Chedraoui) - Radio Edit - Hermanos Inglesos",
  "Shake Me - Radio Edit - Jean Elan",
  "Feels So Good - Armin van Buuren",
  "Freak - Housetrap",
  "Castle In The Snow - The Avener",
  "Degtuku Nesinesioju - Ionrec",
  "You Want Me - Tom Zanetti",
  "All About the Bass - Radio Edit - The Sneekers",
  "My Love (feat. Jess Glynne) - Route 94",
  "DJ Is Your Second Name - C-BooL",
  "Dynamite (feat. Sebastian) [Radio Edit] - Kraak & Smaak",
  "Kaya - Radio Edit - Androma",
  "Less Is More - Calvin Logue",
  "On Your Mind - Diversion",
  "Do You Realize - Original Mix - Sasha Fashion",
  "They Don't Know - Radio Edit - Disciples",
  "Just a Bitter Love - The Dead Rose Music Company",
  "Runway - For Club Play Only, Pt. 5 - Duke Dumont",
  "Sweetest Thing - Club Mix - Just Kiddin",
  "Day Dreams - Midi Matilda",
  "The Strongest of the Strange - Av.i",
  "Roses - ABRA",
  "Dance - Radio Edit - Max Manie",
  "Strange Is Better - CHINAH",
  "Anyone - CHINAH",
  "Cooler Than Me - Lucky Luke",
  "Olivia - Satin Jackets",
  "My Love - Martin Solveig",
  "Customer Is King - Solomun",
  "Soulmatic - Purple Disco Machine",
  "Resentment - BLOW",
  "Perfect Love (Pt. 1) - Amine Edge & DANCE",
  "Riverside 2099 - Oliver Heldens",
  "Beautiful Things - Kastis Torrau & Donatello Remix - Andain",
  "#зажигалка - Sweetie Sad",
  "RWB - ALEXEMELYA",
  "No Sleep - ALEXEMELYA",
  "Lonely In The Morning - ALEXEMELYA",
  "Never Freak - Endor",
  "1998 - AtariJones",
  "Space to Pray - Driule XL",
  "Paranoid - Lauv",
  "Another Case - Tora",
  "Night Flight - Franc Moody",
  "Bonfires - Elder Island",
  "Alles - Dub Version - Perel",
  "Front of Us - Pontifexx",
  "Party Rockin (Esbórnia) - Vintage Culture",
  "I'm Not Alone - Radio Edit - Calvin Harris",
  "My Love (feat. Jess Glynne) - Route 94",
  "Me, Myself & I (feat. Bryn Christopher) - Blonde",
  "Takes A Little Time - Zac Samuel",
  "Girl - TR456 - Sirkea",
  "Comes In Waves - Total Giovanni",
  "Pachniesz Owocami (Frivolous Remix) - Piotr Bejnar",
  "So Real - Deutsch Duke",
  "Surface Tension - Tomos",
  "Midnight Love - Original Mix - Chez Moon",
  "Next Time - Utrecht",
  "Breath Hold - Fellini Félin",
  "Figured Out - Jonny Reebok Remix - ALTA",
  "At Sea - Godwolf Remix - Flamingo",
  "Kingswing - Matador",
  "Itajai - Matador",
  "Sunburn - Matador",
  "Los Pistolos - Original Mix - Julian Jeweil",
  "Overtime - Jessie Ware",
  "Drive Slow - LUCASV",
  "So Love (feat. Shaan Singh) - Pacific Heights",
  "Nandoo - Sam Shure",
  "Ease Up (Will Clarke Cuddles At Sunset Remix) - Justin Jay",
  "Never Get To You - Moon Boots",
  "No Less - SG Lewis",
  "Blue Tuesday - Delphi",
  "Parallel Lines - BAILE Remix - Sterling Grove",
  "Spooky Self - Audio Dope Remix - Don't Kill The Beast",
  "Clap Your Hands - Art of Shades",
  "Opal - Four Tet Remix - Bicep",
  "Lullabies - Adventure Club Remix - Yuna",
  "Tell Me Why (feat. Celeste) - Pink Panda",
  "Tell Me Why - Eleonora",
  "Territory - The Blaze",
  "Stil - Acid Arab",
  "Nineteen Eighty-Two - Original Mix - Moscoman",
  "He Not In - Chicken Lips",
  "Italove - EMMANUELLE",
  "Ciquita - Ransom Note Edit - Bawrut",
  "(It Happens) Sometimes - Jack Back",
  "Where I'm Going - Jerry Folk",
  "Cola - Simon Mills Full Sugar Mix - CamelPhat",
  "united states of smash - bucket 桶",
  "Give It - Betta Lemme",
  "Zion - Fluke",
  "Sub Zero - Emr3ygul Remix - Slame",
  "Black Bimmer - Linius",
  "Woohoo - HOSH",
  "Cut Me Loose - Shelter Point",
  "Supercool Funky Lady - Laid Back",
  "Witch Doctor - Crazy P",
  "So Hot - Anabel Englund",
  "Sweet Melodies - Schier Remix - Lizzy Land",
  "Liverpool Street In The Rain - Mall Grab",
  "Easy Way Out - LEISURE",
  "make a move - nørus",
  "Vizzi Vazzi - Lauer",
  "I Saw Her Kiss Him in Front of Me and I Was Like Wtf? - DJ Seinfeld",
  "Ash - Henry Krinkle",
  "Embrace - Durante",
  "Because You Move Me - Extended Mix - Tinlicker",
  "Thinking Of You - Serge Devant",
  "What It Feels Like - Radio Mix - Sons Of Maria",
  "Gotta Have U - Touch & Go",
  "Clap Your Hands - Solomun Remix / Radio Edit - Whilk & Misky",
  "Not Alone - Time",
  "Drowning - Radio Edit - Robosonic",
  "Changes - Radio Edit - Strange Loving"
];
result2 = [
  "Reality (Dwin Remix) - SI$HA",
  "Wish - Elekfantz",
  "Fuse - Shelter Point",
  "Searching For - Xinobi",
  "Flirtatious - Just Us",
  "Domino - Rework Edit - Oxia",
  "Fireburn - De Hofnar",
  "Starscream - DBMM",
  "Move Magic - Julian Maverick",
  "Last Thoughts - Grandlife Remix - Napkey",
  "Trippin - Gabe Remix - Bondi",
  "Reality (Dwin Remix) - Dwin Remix - SIHA",
  "Sacrifice - Original Mix - Simian Mobile Disco",
  "Trndsttr (feat. M. Maggie) - Lucian Remix - Black Coast",
  "What They Say - Maya Jane Coles",
  "Carrousel - Short Version - N'to",
  "This World - Zero 7",
  "Me & You (feat. IRO) - Alok",
  "Beautiful Mind - Kiki Doll",
  "Falling - Misha Klein, No Hopes Radio Remix - MCB 77",
  "Full Moon - Barkley",
  "Porto Hustle - Ben Delay Remix - Chris Montana",
  "Crossover - Vanilla Ace",
  "Feel Inside - Namatria Remix - Johnny Astro",
  "G Strike - Alex Twitchy & Tewax Remix - Vasi",
  "Up & Down - The Bestseller",
  "How Does It Feel - Original Mix - Natema",
  "Coming Home - Original Mix - Funkerman",
  "2127 - Eminence",
  "It's Not Enough - Radio Edit - Dusky",
  "Say You'll Stay - House Mix - Trutopia",
  "She's a Gun - Christopher Norman Remix - Newtimers",
  "Like An Animal (Yotto Remix) - RÜFÜS DU SOL",
  "Budapest - A2A RMX - George Ezra",
  "Get Lost - Paul Damixie",
  "Melody - MOUNT",
  "Tell Me - Secrets Mix - Chris Malinchak",
  "Make Love - Joe Stone",
  "Love On Hold (feat. Tawatha Agee) - Aeroplane",
  "The Feels - JackLNDN",
  "Brilliance - Lipless",
  "Feel Fine - Patrick Lite",
  "Lost in the Moment - Darius",
  "Evil Twin - Freaks On Floor",
  "Young Rich And Radical - Radio Mix - Club cheval",
  "Sweet Harmony - Short Edit - Sans Souci",
  "Peaking - William French",
  "Don't Try - Stereoclip",
  "Marijuana - Chrome Sparks",
  "Dreamer - Sako Isoyan",
  "Toi Et Moi - Lifelike Remix - Paradis",
  "Clean Slate - Joachim Pastor",
  "Make You Mine - Original Mix - Justin Jay",
  "Close To You - Icarus Edit - ARLE",
  "Drowning - Djuma Soundsystem Remix - Robosonic",
  "Les Djinns - Trentemoeller Remix - Djuma Soundsystem",
  "Disambigua - KatrinKa Edition - Djuma Soundsystem",
  "I'm So High - Norwood & Hills",
  "Little Babylon - Jyye Remix - Polina",
  "The Blues (Fynn Remix) - Niklas Ibach",
  "Burst A Run - Original Mix - KVPV",
  "Why Does My Heart Feel so Bad - Enrico Sangiuliano Remix - Moby",
  "Keep Believing - Tosel & Hale Remix - Anton Ishutin",
  "Burlesque - A.Squared",
  "Bigger Than Prince - Hot Since 82 Remix - Green Velvet",
  "Pronoia - Trilucid Remix - Matter",
  "Get Down - Hugobeat Remix - Branzei",
  "Love Shy - James Hype Remix - Kristine Blond",
  "Tell Me - Radio Edit - VINNE",
  "The Full Of The Moon - Martin Lu",
  "Forever - Cropper",
  "Sweet Love (Calling Out Your Name) - Bolier",
  "Why - Voyeur",
  "No Eyes - Claptone",
  "Free - Giorgia Angiuli",
  "For You - Original Mix - Melih Aydogan",
  "Free - Original Mix - Kilian & Finn",
  "Space Junk - Flow & Zeo Remix - Uone",
  "Change - Sven Tasnadi",
  "Lose Control - Alexander Holsten",
  "FYOF - 219 Boys",
  "Away From Home - Radio Edit - PHAM",
  "October - Icarus",
  "You and the Music - Helvetic Nerds",
  "Good Together - Punctual Remix - HONNE",
  "Drowning (feat. BADBADNOTGOOD) - Mick Jenkins",
  "Starlings - Henry Saiz Remix - N'to",
  "Fight For Love - Martin Lu Remix - Delusion",
  "Atlas - Adriatique Remix - Marc Romboy",
  "Leave the Clouds Behind You - Sound Remedy",
  "The Boy is Mine - Mark Lower Vocal Edit - Ben Delay",
  "What Happened (Future Access Remix) - Future Access",
  "Back to You - Digital Farm Animals and Louis Tomlinson Remix - Louis Tomlinson",
  "Moments in Love - Art Of Noise",
  "Move You - Night Tales",
  "Lost Yourself (feat. JT Mak) - The Golden Pony",
  "Days of Lavender - Amtrac Remix - Promises Ltd.",
  "Sacred Dance Of The Demon - Gorgon City Remix - Damian Lazarus",
  "Say You're Mine (feat. Mari.M) - TR403 - Kisch",
  "Love All Day feat. Leela D - Radio Edit - Kisch"
];
result3 = ["BOOM - Mixcut - Tiësto",
"Be Here - Duke Dumont",
"Black Paradise - Lowheads",
"Would I Lie to You - Deep House Remix - Christian Joseph",
"SHY (feat. Brayton Bowman) - Club Mix - The Magician",
"Real Life - Duke Dumont",
"MIC Drop (feat. Desiigner) [Steve Aoki Remix] - BTS",
"Polaris - Dee Montero",
"Jump Up - Sharam Jey",
"Star - Original Mix - KVPV",
"Velum - NBSPLV",
"Бутылочка - Luna",
"Diving with Whales - Daniel Portman Radio Mix - Nora En Pure",
"Nocturnal - Disclosure V.I.P. - Disclosure",
"Sunshine - Original Mix - KVPV",
"Mars - Valy Mo",
"Fall Together - Pomo",
"Loving Life - Franky Rizardo Remix - Rationale",
"Loving Life - Rationale",
"Lost in the Night - THBD",
"Loan My Eyes - Part of me",
"Moon Rocks - Enrico Sangiuliano",
"Perfect Lady - Original Mix - Made To Move",
"Age Well - Ten Walls",
"Slow Bilbao - Compuphonic",
"Løve Me - Torren Foot",
"Dreams - Carsky",
"Andromeda (feat. DRAM) - ZHU Remix - Gorillaz",
"Feel It Still - ZHU Remix - Portugal. The Man",
"A Night Like This - Richie Hawtin's A Dub Like That Remix - Steve Bug",
"The Finishing - Stavroz",
"Companions - Amtrac",
"Without You - Original Mix - Mahmut Orhan",
"What I Need - Original Mix - Mika Olson",
"Space - Radio Edit - YNC X S3RIOUS",
"Melrose - SNBRN",
"White Lack - InClose",
"48HRS - Extended - Disciples",
"Fight Clubs Are Real - Cliff Martinez",
"Know Where - Holy Other",
"W / O U - GEMS",
"Walk With Me - Alex Stavi",
"Be Randy - Dom Dolla",
"Crazy over You - Original Mix - Earstrip & Torha",
"Chicago - Original Mix - Flow & Zeo",
"I Wait - Mall Grab Remix - Ron Blanco",
"Время Ток (Sudorgy Remix) - Antoha MC",
"Dynamite - Original Mix - Hot Light",
"Prepare for the Night - Croatia Squad",
"The Giver (Reprise) - Duke Dumont",
"Motorola - Gorgon City",
"No Sleep - Kaskeiyp Remix - Vanotek",
"Ibiza 77 (Can You Feel It) - Oliver Heldens",
"Lingua - Sub Focus",
"Got U (Ready or Not) - Kokab",
"Sunglasses at Night - Radio Edit - Bodybangers",
"White Poison - Unholy",
"Man With The Red Face - Radio Edit - Mark Knight",
"At Night - Album Mix - Shakedown",
"On My Mind - 3LAU",
"We Were Young - Shavi",
"I Am God - Wolfstream",
"I Want Your Attention - Moon Boots",
"MIND (feat. DOC, Goodmorning) - Bobby Nourmand",
"Last Glow - Kartell",
"Long Time Coming - KAASI",
"Lyra - Huxley",
"Over U - Stwo",
"Ready (Sevnth Remix) - Azad",
"All Alone - Stwo",
"Tell Me Why - Marcus Schössow",
"Rhythm Of The Night - Original Mix - Fedde Le Grand",
"Exhale - Ian Edson",
"Hush - Alyx Ander",
"Love - JOUR",
"K. - Cigarettes After Sex",
"Help Me Lose My Mind - Disclosure",
"The Fall - Radio Edit - Himbrecht",
"Pussy - Nick Monaco",
"Nevermind (Wankelmut Remix) - Dennis Lloyd",
"Drop the Pressure - Beni",
"In The Wild - Dee Montero",
"Starchild - Tensnake Remix - Boys Noize",
"It's Not Over - Jordan Burns",
"As I Sleep (feat. Charlee) - Tobtok",
"Wolf Country - Durante",
"Vinternatt - Danijel Kostic",
"Little Time - Catz N Hood",
"Merriwa - Set Mo",
"Acid - Fast (Alin Dimitriu Remix) - Otherside",
"Batshit - Sofi Tukker",
"6 Days - Mahmut Orhan",
"Without You - Original Mix - Mahmut Orhan",
"Дисконнект - Allj",
"Happy Man - Jungle",
"Stormy Love, NM. (feat. JOY.) - ZHU",
"Mad-Ma - GAZIROVKA",
"Best Friend - Remix - Sofi Tukker",
"It Wasn't Meant to Be - Theo Kottis",
"Notice Me - Migos",
"Real Life - Terrace Dub - Duke Dumont"];
result4 = [  "Lost - Boris Way Remix - Roman Kouder",
"The Magic Room - Dino Lenny & Seth Troxler Re-Edit - Dino Lenny",
"Mountain - Joachim Pastor",
"Pheromones - Franc Moody",
"Play (Groove Junkies Original Mix) - Groove Junkies Original Mix - Groove Junkies",
"Mystical Science - Modest Crow",
"La Storia del Tempo (Jikan No Rekishi) - Never Lost",
"Split Wick - Durante",
"Paseo De Los Tristes - Britta Unders Happy Camper Remix - Hraach",
"Stressed Out - Twenty One Pilots",
"Sylvia Says (Tensnake Remix) - Charlotte Gainsbourg",
"Love Stream - Mat.Joe",
"Love Stream - Radio Edit - Mat.Joe",
"Disco Night - Kungs",
"Rolling - Radio Edit - PressPlays",
"Back Again - Lykov",
"Siriusness - Club Cut - Betoko",
"Phantasy - Betoko",
"Leaving Tonight - Martin & Rami",
"Moving Groove - Radio Edit - Filatov & Karas",
"We Are - Dwin",
"Punk - Vocal Radio Edit - Ferry Corsten",
"You Got Me - Radio - Saxtone",
"Lethal Industry - Radio Edit - Tiësto",
"Set The Stakes High (Radio Edit) - Heather Leigh West",
"Colours In The Sun - Sander Kleinenberg",
"Let Me - Ilkay Sencan",
"Greece 2000 - Sebastian Davidson & Melosense Remix - Three Drives On A Vinyl",
"Lovesick - Lindstrøm",
"Your Shhh - House Mix - Quentin Van Honk",
"Dopamine Machine - CamelPhat",
"Don't Break My Heart - Tiga",
"Wavey (feat. Alika) - CLiQ",
"Nauji metai - Sweet Euphony Remix - Antis",
"American Dream - Super3",
"Viens me chercher - Radio Edit - Charlotte",
"The Mood - stefan",
"Keep Rolling - Nils Hoffmann Remix - Philipp Wolf",
"Sun My Sweet Sun - Red Axes",
"Bloody Shadows from Afar - Lena Platonos",
"Resonance - Home",
"Summer - Vanilla",
"As I Sleep (feat. Charlee) [Gramercy Remix] - Tobtok",
"Time To Dance - Sebastian Remix - The Shoes",
"You Keep Comin’ - Hannah Wants",
"Suma Lie - Olsvangèr",
"Man of the Land (feat. Real Lies) - Icarus",
"Hysteria - VIP Mix Edit - Just Kiddin",
"Karma - Club Mix - KVPV",
"Sideways - NBSPLV",
"Street Lights - Daddy Was a Milkman",
"Lafayette - Cassian",
"Trap & Deep - The First Station",
"Seasons - Dapa Deep",
"Saxyness - Never Dull",
"W.I.Y.M - Pyramid",
"Out of Touch - Lucky Luke",
"Madness to Mayhem - Amtrac",
"Lioness - Nora En Pure",
"Drama Free - deadmau5",
"Humano - Victor Ruiz Remix - Dubfire",
"Wave 100 - Rhode & Brown",
"New Ones (Just Kiddin remix) [Radio Edit] (feat. Aaron Camper) - Hollaphonic",
"Bass (Hold On) - Dubdogz",
"In a Spasm - Novar",
"Wrong Crowd - Purple Disco Machine Remix - Tom Odell",
"Parfume - Eli & Fur",
"Irréversible - Private Agenda Remix - Fhin",
"Nightbird - Deep Active Sound",
"Bassment Dweller - Original Mix - Jesse Bru",
"Treasures - Adam Vitali",
"Desire - Cut Snake",
"I Wanna Rock You - Denis Naidanow Mix - Giorgio Moroder",
"S.O.S. - Keller",
"Kalacol - Red Axes",
"Beloved - Dj Vianu",
"GOAT - Jopez",
"Skylines - Zekl",
"Supergirl - Max Oazo",
"Pink Industry - Original Mix - Manfredas",
"Dance to Hits - Xinobi",
"Clap Your Hands - Karma Kid",
"Paradise - Payfone",
"Native Talk - Volta Cab",
"Out Of My Head - Darrell Story",
"Night Drive - Gorgon City",
"No Distractions - Vestalus Remix - Semi Precious",
"Hidden - Ten Walls",
"Laïka (Hannes Fischer Remix) - Camel Power Club",
"Talk (feat. Linae) [Cápac Remix] - Oliver Nelson",
"Augo Sode Klevelis, Klevelis - Saulius Spindi",
"Cold - UNKLE Remix (Edit) - Editors",
"Haste - RY X",
"Violet City - Mansionair",
"Daily Dancer - Damny",
"Bad Kingdom - Moderat",
"Yeah - Edit - Set Mo",
"Myli - Julian Jeweil",
"Heroes (we could be) - Amtrac Remix - Alesso",
"Atheist - Latmun Summer Dub - Disciples",];
result5 = [  "Let You Go - Vhyce",
"Otic - Alex Metric",
"Sun - Radio Edit - Dayne S",
"Meine - Daso",
"TRAP - DEEP MIX - Paolo Paletnologo",
"I Feel - Kolombo",
"Chamber Of Reflection - Mac DeMarco",
"Moonlight Ride - Issac Chambers",
"Do Ya Thing - Sneaky Sound System",
"Move Your Body (Future House) - Tchami",
"The Way You Move (feat. Kamaliza) - Falqo",
"Cherry Bomb - Maya Jane Coles",
"Dreaming - Frost",
"Midnight on Rainbow Road (Beat Edit) - Leon Vynehall",
"Don't Slow Down - Original Mix - Pascal Junior",
"Can't Get You out of My Head - Melih Aydogan",
"Work - Driule XL",
"Rain Land - Driule XL",
"Right On Time - Original Mix - Chris Lawyer",
"Funk Me up Baby - Alex Cortiz",
"Santa Monica Drive - Alex Cortiz",
"Going Down South - Adani & Wolf",
"Elephants - Original Mix - PHCK",
"When You Go Wrong - GytisJ",
"Afterglow - Frost",
"The Encounter - Original Mix - Evren Ulusoy",
"Emperor Love - RockyRocky",
"Hold Me - M&D Substance",
"Taken By A Stranger - Lena",
"Feels Just Like it Should - Timo Maas Remix - Jamiroquai",
"Maybach - Myngo",
"Domino - Matador Remix - Oxia",
"All You Need Is Lovin - Radio Edit - The Sneekers",
"Muzikos - Papuga Remix - The Sneekers",
"I'll Be There (To Catch You) - Original Mix - MAM",
"Twilight (feat. Frankie Beverly) - Maze",
"Gotham City - The Beatangers",
"World In Action - Mat.Joe",
"Panic Room - Au/Ra",
"Street Player - DINKS",
"Chloe - Original Mix - KVPV",
"Alexandra - Wayward",
"Muzzika - Betoko",
"No Turning Back - Original Mix - Tosel & Hale",
"One Kiss (with Dua Lipa) - Oliver Heldens Remix - Calvin Harris",
"The Animal Inside - Gabriel Ananda Remix - OHMYBOY",
"Artifacts - Rezident",
"Thunda (feat. John Mendelsohn) - Remastered - Honey Dijon",
"Que Rico - Original Mix - Gary Caos",
"Underworld - Tuff City Kids Remix - Edu Imbernon",
"Pump Up The Volume - Noisy Bears",
"Down Wid Da - David Penn",
"My Babe - Me & My Toothbrush Remix Edit - Alex Kenji",
"We Do It (feat. C-Fast) - Leandro Da Silva",
"Dance a Little Bit Closer - Babert",
"Sunny Day - Vocal Mix - Earth n Days",
"Free Me - KI Creighton",
"Midnight Cruise - LTGTR",
"Miracle - Giorgia Angiuli",
"Timeout - Felon",
"Attack Disco - Maksim Dark",
"Strange Attack - Cosmic Boys",
"Dream On - Moullinex",
"Twin - Fabian Kash",
"Bright Lights - Original Mix - Diversion",
"The Longest Road (feat. Lissie) - Morgan Page",
"Own the Night - JazzyFunk",
"Pink Panther - Solee",
"On TV - Club Mix - Kostya Rhino",
"Zebra's Call - Original Mix - Solunn",
"Forever After - Anturage Remix - Anton Ishutin",
"Empty Streets - Cyantific",
"She's Bad - Boogie Bitches",
"You Remind Me - Recognise",
"Old Times (feat. Anabel Englund) - Amtrac",
"Arty Boy - Set Mo Remix - Flight Facilities",
"So Long - Edit - Made By Pete",
"The Sky And The Earth - Original Mix - Newman",
"Worship - Golden Features",
"Get Into It (feat. Loreen) - 1994 Edition - Boston Bun",
"Heart-Shaped Box - Imad Royal",
"Maniac - Original Mix - KVPV",
"Chicki - Said Energizer",
"Black Suit - Original Mix - KVPV",
"I Made You Do - Melih Aydogan",
"Imprint - NBSPLV",
"Melancholy - NBSPLV",
"Rising - Teenage Mutants",
"3 Million - Avicii feat Negin",
"Loving You - Pryda",
"The Space In Between - Jan Blomqvist",
"24 Hours of Night - Said Energizer",
"Just Friends - Paul Woolford Dub - Hayden James",
"Nevermind - Original Mix - KVPV",
"Typically Her (Kaytranada Edition) - Beverlay",
"We Can Be Together - XYPO",
"Never Let Me Go - Lady Ocean",
"Oasis - Kyco x Barkley Remix - The Him",
"I'm Your Love - Kenno",
"Traffic - Radio Edit - Tiësto",
"Push The Feeling On - Mk Dub Revisited Edit - Nightcrawlers",
"Jackie Chan - M-22 Remix - Tiësto",
"Hang Up Your Hang Ups (The Only One) [feat. Kim English] - CamelPhat Remix, Edit - Paul Woolford",
"Let's Chat (feat. Pony) - Paris & Simo",
"First Last Kiss - JYYE Radio Edit - LÜCKS",
"Fooling Me - JYYE",
"Feel It - Ivan Gough Dub - ARLE",
"Voice Of Silence - Edit - Cristoph",
"Show You - Wankelmut",
"Cafe Del Mar (Tale Of Us Renaissance Remix) - Energy 52",
"Use Me Up - CID",
"Freak Like Me - Alexis Troy",
"Passenger Seat (Future House Remix) - Mlodic",
"Panic Room - Club Mix - Au/Ra",
"The Heart Is A Woman - Rodriguez Jr.",
"Lake Arrowhead - Passenger 10 Remake - Nora En Pure",
"Days Without You - Crussen Remix - Satori",
"Another One Bites the Dust 2018 - Andrey Exx",
"FTPA - Gorgon City",
"Crash - Chris Malinchak",
"Reckless - Sion",
"Capricorn - Elderbrook",
"Go Head Be Gone - Ramon Kreisler",
"By My Side - Clubbers",
"Jealousy - Disciples",
"Red Lights - Stephan Duy Remix - Marcus Schössow",
"Intimidating Love - Endor Remix - S-Man",
"Problem - Daniel Fernandes",
"Pop That Thang - Daniel Fernandes",
"Give You Ride - Daniel Fernandes",
"Got This - Daniel Fernandes",
"Little Bad Bitch - Daniel Fernandes",
"Young King - Daniel Fernandes"];
result6 = [  "Darkest Sound - Amtrac",
"God Is a DJ - Faithless",
"Insomnia - Faithless",
"Good Grief - Autograf Remix - Bastille",
"Rooftop - Nude",
"Escape - Saavan",
"Gdbye - MOONZz",
"Deep Fear - Phobia Radio Edit - Sidekick",
"Dirty Ol' Man - Faithless",
"We Come 1 - Radio Edit - Faithless",
"Nobody Rules the Streets (feat. Louisahhh!!!) - Brodinski",
"Bury Me - feat. Maluca & Bricc Baby Shitro - Brodinski",
"Dreams - ZHU",
"Вите надо выйти - ESTRADARADA",
"Мы сделаны из звёзд (Когда ты меня целуешь) - ESTRADARADA",
"Umf 2/3 - ESTRADARADA",
"Sometimes Things Get, Whatever - deadmau5",
"With You - Crystal Skies Remix - ILLENIUM",
"Let Go - deadmau5",
"Stylo (feat. Mos Def and Bobby Womack) - Radio Edit - Gorillaz",
"Wasted Youth - Highly Sedated",
"Electrify (feat. Scott Mellis) - Oliver",
"Another Lie - Dapa Deep",
"Day and Night - Lo Air",
"Call Me Now - Namatria Remix Edit - Lisitsyn",
"Running Away - Way Out West",
"You Get My Drop - Karpovich",
"Somebody to Love - Kyrill & Redford",
"Up and Down - Kattison",
"Post Modern - Running Touch",
"Empty Floor - Jan Blomqvist",
"Always Gonna Be (feat. Alex Mills) - Low Steppa Remix - Sonny Fodera",
"Wicked Game - Radio Edit - Stefan Gruenwald",
"Love Like Mine - Cleopold Remix - Miami Horror",
"No Fun - Golden Features Remix - The Presets",
"Luv Deluxe - Cinnamon Chasers",
"Berlin - Underset",
"Sandburg - Tinush",
"Chicago - Original Mix - Apres",
"All I Want - Bob Moses",
"Future Soup - Autograf",
"Bright Lights - Vandelux",
"Come Fly Away - Soha & Adam K Remix - Benny Benassi",
"Passage - Esteble",
"Miradors - Jody Wisternoff & James Grant Remix - Solomon Grey",
"Nobody Knows (feat. WYNNE) - Autograf",
"I Can See It - Miguel Migs Salted Vocal Mix (TR317) - Lisa Shaw",
"Close to You - Sugar Hill",
"Solaris - Nunaki",
"Cocaine - Phantoms",
"Lost You - Juan Calderon",
"Colorful - Kúra",
"Need To Feel Loved - Adam K & Soha Vocal Mix - Reflekt",
"Victor Weed - Grey Killer",
"Fill Me In - Loud Luxury",
"Make Me High - LiTek",
"We Can Be Together - Extended Mix - XYPO",
"It's Strange (feat. K.Flay) - Win & Woo Remix - Louis The Child",
"My Love - Stoto",
"Tell Me - Constant Z",
"House Of LSD - K1W1 & Alodot Remix - Alodot",
"Mystery - The First Station",
"Bad Boys Cry - Original Mix - Mark Lower",
"Peace - Kenton Slash Demon",
"Follow You Down - Oliver Schories Remix - Just Her",
"Falling In Love Again (feat. Erik Hassle) - Vario Volinski Club Vocal - Vario Volinski",
"Alright - Radio Edit - Mark Knight",
"Rhymes - Hannah Wants",
"Rhymes - Sonny Fodera Remix - Hannah Wants",
"Just (feat. Kristine W) - Illyus & Barrientos Remix - Hannah Wants",
"Hidden Love - Hannah Wants",
"Apolune - Jesper Ryom",
"The Fourth - Original Mix - Chris Malinchak",
"Drinkee - Vintage Culture & Slow Motion! Remix - Sofi Tukker",
"Better Day - illusionize",
"Roll It - illusionize",
"Bring It Baby - Original mix - Gabriel Boni",
"B.O.W - Slow Motion",
"Blessed - Original mix - Slow Motion",
"Eli Eli - Maduk Remix - Misun",
"Rollercoaster - Maduk Remix - Low5",
"Sunlight (feat. Years and Years) - Darius Remix - The Magician",
"Need To Feel Loved - Sander van Doorn",
"Coreless - Murphy Cooper",
"Les Djinns - Djuma Soundsystem",
"Sunhump 2006 - Radio Edit - Richard Durand",
"R.Y.A.N.L. - Pleasurekraft Remix - Sander Kleinenberg",
"World Hold On - Radio Mix - Vitaco",
"Where Is My Ego ? - (Dim Sum Remix) - Husbands",
"Easy - Florian Paetzold",
"Panorama - Møme",
"I Feel You - Original Mix - Tough Love",
"Fade - Watermät",
"Live Alone - Yuksek",
"Keep Up - Noir",
"Angetenar - Rompasso",
"Man Gone - Tube & Berger Remix - Weiss (UK)",
"With Me - Lane 8",
"Deep Sea Blue - Alle Farben",
"Claro - Arthur Oskan"];
